name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: push docker image to docker hub  
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo 
        uses: actions/checkout@v2

      - name: login to dokcer hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # GitHub secret for Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}   # GitHub secret for Docker Hub password

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hadiya_frotend:latest .
        
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hadiya_frotend:latest
