apiVersion: v1
kind: Secret
metadata:
  name: aws-ecr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMybGtNalV4TmpwVGFXUXVZWE15TlRFMiIKCQl9Cgl9Cn0=
